### ISSUE TITLE
install.sql doesn't work with MySQL versions over 5

### ISSUE THREAD

**Issue by download13** [LiveHelperChat/automated-hosting#3]
I noticed that when trying to use the install script on MySQL 5.7, I get the following error:

```
ERROR 1101 (42000) at line 1: BLOB/TEXT column 'phone_number_data' can't have a default value
```

From what I can tell, it's related to [this issue](http://bugs.mysql.com/bug.php?id=21532) on the MySQL bug tracker.

What is the easiest way to fix this? Can the TEXT columns just be swapped out for VARCHAR or some other string type that allows defaults, or can it be made to do without defaults?

We could always just use a different database that support defaults on TEXT columns, but that might be more difficult than fixing this. I'd like to hear your thoughts on the matter.

**Comment by remdex** [comment]
Hi,
Most likely I'll just remove default value. If you wish you can create pull request also :)

**Comment by download13** [comment]
In that case I'll edit it for our production version and if that works I'll make a pull request out of it.

Is there a danger that any of the PHP code relies on the default values being there and will crash without it?

**Comment by remdex** [comment]
Nop

On Thursday, July 23, 2015, Erin Dachtler <notifications@github.com> wrote:

> In that case I'll edit it for our production version and if that works
> I'll make a pull request out of it.
>
> Is there a danger that any of the PHP code relies on the default values
> being there and will crash without it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiveHelperChat/automated-hosting/issues/3#issuecomment-124216909>
> .
>


-- 
Sincerely,
Remigijus Kiminas
