### ISSUE TITLE
Extending limitations parameters

### ISSUE THREAD

**Issue by a7medo778** [LiveHelperChat/automated-hosting#7]
hey guys, so i just stumpled upon this and still doing some digging around.

is it possible to extend the plugin parameters to include the number of agents, or additional activated channels ?
mostly for upselling, 3 agents in base plan, then x for each additional agent
or 1 channel is included, each external channel costs X to be activated

**Comment by remdex** [comment]
Hi,

No this plugin does not support max agent. So you would need to implement it yourself using hooks :)
To limit how many agents can work under one account you can by setting 
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/settings/settings.ini.default.php#L19 to true.

So the only thing is you need to extend this plugin just :)

**Comment by remdex** [comment]
Actually just checked there is "max_operators" attribute. So the only thing you need to extend is "instance/modules/lhinstance/registerinstance.php" and save this field within request :)
